# For M5 Max 32GB, use these settings:
# elasticsearch: ES_JAVA_OPTS=-Xms6g -Xmx6g, mem_limit: 8g, mem_reservation: 6g
# fluent-bit: mem_limit: 1g, mem_reservation: 512m
# kibana: NODE_OPTIONS=--max-old-space-size=1024, mem_limit: 2g, mem_reservation: 1g

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      # - ES_JAVA_OPTS=-Xms512m -Xmx512m
      # - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - ES_JAVA_OPTS=-Xms4g -Xmx4g  
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./config/elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    # mem_limit: 3g         # Limit container memory
    # mem_reservation: 2g   # Reserve memory

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.12.2
  #   volumes:
  #     - ./config/logstash/pipeline:/usr/share/logstash/pipeline
  #     - ./config/logstash/config:/usr/share/logstash/config
  #     - ./data/logs:/logs:ro
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy
  #   ports:
  #     - "9600:9600"
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9600"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  fluent-bit:
    # image: fluent/fluent-bit:latest
    build:
      # context: .
      dockerfile: fluent-bit.Dockerfile
    volumes:
      - ./config/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./config/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ./config/fluent-bit/decompress.lua:/fluent-bit/etc/decompress.lua:ro
      - ./config/fluent-bit/extract_path_metadata.lua:/fluent-bit/etc/extract_path_metadata.lua:ro
      - ./config/fluent-bit/delay.lua:/fluent-bit/etc/delay.lua:ro
      - ./data/logs:/logs:ro
      - ./data/fluent-bit/tmp:/tmp
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "2020:2020"  # Fluent Bit HTTP server for metrics
    environment:
      # - ES_JAVA_OPTS=-Xms6g -Xmx6g
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - TZ=UTC
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./config/kibana:/usr/share/kibana/config
      - ./data/kibana:/usr/share/kibana/data
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  es_data: